### ISSUE TITLE
Extra plugins installed

### ISSUE THREAD

**Issue by lamberta** [pedropenna/Intellij-Zenburn#3]
Enjoying the your implementation of the Zenburn color scheme in Android Studio 1.5, thanks!

When importing the jar, it also installs the plugins _Acejump_ and _Key promoter_ (which in turn need to be updated and have the editor restarted). While maybe useful plugins, should these be considered outside of the scope of this color scheme project and stripped? They seem to add a little friction and confusion.

**Comment by 0jrp0** [comment]
+1. I also received a request to update these extra plugins that I don't use directly.

**Comment by pedropenna** [comment]
Oops!
My bad! :)
