### ISSUE TITLE
Consider new color for enum values

### ISSUE THREAD

**Issue by 0jrp0** [pedropenna/Intellij-Zenburn#4]
Enum values such as Foo.THIS_VALUE are being colored in a dark purple. Consider using another color that contrasts better.

**Comment by pedropenna** [comment]
Hi! I'm having a hard time trying to reproduce this.

In both my Intellij version 13 and Android Studio the enum values appear as light blue.

Which Intellij version are you using?

**Comment by 0jrp0** [comment]
I'm using Android Studio, but it's a custom build. Is there anyway I can highlight the text and find what color attribute it got it from? Or perhaps a color dropper plugin that does this? Or do I have to parse through all the color settings?

**Comment by igorepst** [comment]
I think I saw something similar before, although with **different** (and not yours) Zenburn implementation and AS 2 beta, where each beta update changed colors in gradle files (but only in them, if I remember correctly) and I had to untick "use inherited attributes" for some colors.

**Comment by charliegriefer** [comment]
I've got the purple as well. 

macOS High Sierra on a 2017 MBP. 

IntelliJ IDEA Ultimate 2017.3

Added a screenshot here: https://www.dropbox.com/s/0h5st9t3wbq9536/Screen%20Shot%202018-05-17%20at%207.57.51%20AM.png?dl=0
